### PR TITLE
Add instances for apply, applic, func, alt.

### PR DESCRIPTION
**Pull request by chexxor**
I believe you'll want to wait until PSC 0.11 release, which allows people enough time to upgrade their PSC release, as stated in https://github.com/purescript/purescript-foreign/pull/50.

### CODE REVIEW

**Comment by paf31** [comment]
Looks useful. Can you please add these for the other newtypes around `Maybe` in this module?

**Comment by chexxor** [comment]
Sure, I'll take a look.

**Comment by chexxor** [comment]
I added the same instances for `Undefined` and `NullOrUndefined`. I don't know how to use `Plus` and `Alternative`, so I didn't do those.

**Comment by garyb** [comment]
This has been made redundant by the removal of the newtypes in the new version. Thanks though!

**Pull request closed without merging**
